/* SPDX-License-Identifier: MIT */
#pragma once

#define CORNIX_SCREEN_WIDTH 64
#define CORNIX_SCREEN_HEIGHT 128
#define CORNIX_HEADER_Y 3
#define CORNIX_HEADER_HEIGHT 18
#define CORNIX_TEXT_HEIGHT 6
#define CORNIX_HEADER_BOTTOM_ROW (CORNIX_HEADER_HEIGHT - CORNIX_TEXT_HEIGHT)
#define CORNIX_OUTPUT_X 2
#define CORNIX_OUTPUT_WIDTH 18
#define CORNIX_BATTERY_X 23
#define CORNIX_BATTERY_Y CORNIX_HEADER_Y
#define CORNIX_BATTERY_WIDTH 39
#define CORNIX_BATTERY_ROW_HEIGHT CORNIX_HEADER_BOTTOM_ROW
#define CORNIX_BATTERY_LABEL_X 19
#define CORNIX_BATTERY_LABEL_WIDTH 20
#define CORNIX_BATTERY_ICON_X 7
#define CORNIX_ANIMATION_Y 24
#define CORNIX_ANIMATION_HEIGHT 84
#define CORNIX_CAT_SIZE 64
#define CORNIX_CAT_Y (CORNIX_ANIMATION_Y + (CORNIX_ANIMATION_HEIGHT - CORNIX_CAT_SIZE) / 2)
#define CORNIX_LAYER_Y 115
/* Explicit opt-in legacy indicators replace the layer footer. */
#define CORNIX_LOCK_Y 100
#define CORNIX_MODIFIERS_Y 109
