/* SPDX-License-Identifier: MIT */
#pragma once

#define CORNIX_SCREEN_WIDTH 64
#define CORNIX_SCREEN_HEIGHT 128
#define CORNIX_BATTERY_Y 22
#define CORNIX_BATTERY_ROW_HEIGHT 10
#define CORNIX_BATTERY_LABEL_WIDTH 54
#define CORNIX_BATTERY_ICON_X 58
#define CORNIX_CAT_Y 46
#define CORNIX_LAYER_Y 82
#define CORNIX_LOCK_Y 100
#define CORNIX_MODIFIERS_Y 109
