"""Build flash-mapped RGB565 animation frames; Pillow needed only to regenerate.

Original artwork and usage restrictions: ../design/README.md.
No GIF decoder, full-frame allocation or PSRAM is needed on the device.
"""
from pathlib import Path
import hashlib
import json
import struct
from PIL import Image, ImageOps, ImageDraw

PORT=Path(__file__).resolve().parents[1]
OUT=PORT/'main/assets'
OUT.mkdir(exist_ok=True)
W,H=180,180
header=['// Generated by tools/encode-display-assets.py; see design/README.md for artwork credits.',
        '#pragma once','#include <stdint.h>',f'#define CAT_WIDTH {W}',f'#define CAT_HEIGHT {H}',f'#define CAT_FRAME_BYTES {W*H*2}']
manifest={}
for name in ('work','sleep'):
    source=PORT/'design/assets'/f'{name}.gif'
    image=Image.open(source)
    frames=[];ends=[];total=0
    for i in range(image.n_frames):
        image.seek(i)
        frame=image.convert('RGBA')
        canvas=Image.new('RGBA',frame.size,'white');canvas.alpha_composite(frame)
        frames.append(canvas.convert('RGB'))
        total+=image.info.get('duration',100);ends.append(total)
    mask=Image.new('L',(W,H));ImageDraw.Draw(mask).rounded_rectangle((0,0,W-1,H-1),radius=round(min(W,H)*0.12),fill=255)
    data=bytearray()
    samples=ends
    for i in range(len(frames)):
        tile=Image.new('RGB',(W,H),'white')
        sized=ImageOps.contain(frames[i],(W,H),Image.Resampling.LANCZOS)
        tile.paste(sized,((W-sized.width)//2,(H-sized.height)//2))
        tile=Image.composite(tile,Image.new('RGB',(W,H),'black'),mask)
        for r,g,b in tile.getdata():data.extend(struct.pack('<H',((r>>3)<<11)|((g>>2)<<5)|(b>>3)))
    path=OUT/f'cat_{name}.bin';path.write_bytes(data)
    header.append(f'#define CAT_{name.upper()}_FRAMES {len(samples)}')
    header.append(f'static const uint16_t cat_{name}_ends[] = {{'+','.join(map(str,ends))+'};')
    manifest[name]={'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
                    'output_sha256':hashlib.sha256(data).hexdigest(),'frames':len(samples),
                    'frame_ends_ms':ends,'width':W,'height':H,'bytes':len(data)}
(OUT/'cat_frames.h').write_text('\n'.join(header)+'\n',encoding='utf-8')
(OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
print(json.dumps(manifest,indent=2))
