"""Encode Salary Cat GIFs into LVGL 9 indexed monochrome frames and previews.

Usage: python scripts/encode-dongle-cat.py --source-dir PATH
Firmware uses the generated, committed C data; Pillow is only needed to rebuild it.
"""
import argparse
import hashlib
from pathlib import Path
from PIL import Image, ImageSequence

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'boards/shields/cornix_dongle_display/widgets'
SOURCES = {'sleep': 'cat-sleeping.gif', 'work': 'cat-working-3.gif', 'snack': 'cat-working-4.gif'}
SIZE = 32


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-dir', type=Path, required=True)
    args = parser.parse_args()
    c = ['/* Generated by scripts/encode-dongle-cat.py.',
         ' * Artwork: @月薪喵, via myunwang/LLMPET. See ../ASSETS.md.',
         ' * Artwork is not covered by the source code MIT license. */',
         '#include "salary_cat_images.h"']
    h = ['/* Generated by scripts/encode-dongle-cat.py. See ../ASSETS.md. */',
         '#pragma once', '#include <lvgl.h>']
    preview = ROOT / 'images/salary-cat'
    preview.mkdir(parents=True, exist_ok=True)
    for name, filename in SOURCES.items():
        path = args.source_dir / filename
        frames, ends, elapsed = [], [], 0
        with Image.open(path) as gif:
            for frame in ImageSequence.Iterator(gif):
                rgba = frame.convert('RGBA')
                white = Image.new('RGBA', rgba.size, 'white')
                white.alpha_composite(rgba)
                mono = white.convert('L').resize((SIZE, SIZE), Image.Resampling.LANCZOS)
                frames.append(mono.point(lambda p: 0 if p < 150 else 255, mode='1'))
                elapsed += max(20, frame.info.get('duration', 100))
                ends.append(elapsed)
        selected = [frames[0]] if name == 'sleep' else [frames[next(i for i, end in enumerate(ends) if end > t)] for t in range(0, elapsed, 100)]
        c.append(f'// {filename}: SHA256 {hashlib.sha256(path.read_bytes()).hexdigest()}')
        count = len(selected)
        h.extend([f'#define SALARY_{name.upper()}_COUNT {count}', f'extern const lv_image_dsc_t *salary_{name}_frames[{count}];'])
        for i, frame in enumerate(selected):
            # LVGL I1: opaque white palette index 0, opaque black index 1.
            packed = bytes([255, 255, 255, 255, 0, 0, 0, 255]) + bytes(v ^ 255 for v in frame.tobytes())
            assert len(packed) == 8 + SIZE * SIZE // 8
            c.append(f'static const uint8_t salary_{name}_{i}_data[] = {{')
            for off in range(0, len(packed), 16):
                c.append('    ' + ', '.join(f'0x{b:02x}' for b in packed[off:off+16]) + ',')
            c.extend(['};', f'static const lv_image_dsc_t salary_{name}_{i} = {{',
                      '    .header.magic = LV_IMAGE_HEADER_MAGIC,',
                      '    .header.cf = LV_COLOR_FORMAT_I1,',
                      f'    .header.w = {SIZE}, .header.h = {SIZE}, .header.stride = {SIZE // 8},',
                      f'    .data_size = sizeof(salary_{name}_{i}_data), .data = salary_{name}_{i}_data,', '};'])
        c.append(f'const lv_image_dsc_t *salary_{name}_frames[{count}] = {{' + ', '.join(f'&salary_{name}_{i}' for i in range(count)) + '};')
        # Decode the same packed representation before making the scaled preview.
        decoded = [Image.frombytes('1', (SIZE, SIZE), bytes(v ^ 255 for v in bytes(v ^ 255 for v in f.tobytes()))) for f in selected]
        scaled = [f.convert('RGB').resize((240, 240), Image.Resampling.NEAREST) for f in decoded]
        scaled[0].save(preview / f'{name}.gif', save_all=True, append_images=scaled[1:], duration=100, loop=0)
        print(f'{name}: {count} frames, {count * (8 + SIZE * SIZE // 8)} bytes image payload')
    DEST.mkdir(parents=True, exist_ok=True)
    (DEST / 'salary_cat_images.c').write_text('\n'.join(c) + '\n', encoding='utf-8')
    (DEST / 'salary_cat_images.h').write_text('\n'.join(h) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
