"""Generate the pixel fonts from the approved 64x128 display design (no dependencies)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# One hex digit per 4-pixel row. Letter spacing is supplied by the widget style.
SMALL = {
    ' ': '000000', '!': '222202', '%': '922449', '+': '022f22', '-': '00f000',
    '.': '000002', '/': '112488', ':': '020020', '?': '690202', '_': '00000f',
    '0': '69bd96', '1': '262227', '2': '69124f', '3': 'e16196', '4': '99f111',
    '5': 'f8e196', '6': '68e996', '7': 'f12244', '8': '696996', '9': '699716',
    'A': '699f99', 'B': 'e9e99e', 'C': '788887', 'D': 'e9999e', 'E': 'f8e88f',
    'F': 'f8e888', 'G': '788b97', 'H': '99f999', 'I': '722227', 'J': '111196',
    'K': '9acaa9', 'L': '88888f', 'M': '9ff999', 'N': '9ddbb9', 'O': '699996',
    'P': 'e99e88', 'Q': '6999b7', 'R': 'e99ea9', 'S': '78611e', 'T': 'f22222',
    'U': '999996', 'V': '999966', 'W': '999ff9', 'X': '996699', 'Y': '996222',
    'Z': 'f1248f',
}
# The short layer names use the approved 5x7 glyphs; all others use SMALL.
LAYER = {
    'A': [14,17,17,31,17,17,17], 'B': [30,17,17,30,17,17,30],
    'E': [31,16,16,30,16,16,31], 'M': [17,27,21,21,17,17,17],
    'N': [17,25,21,19,17,17,17], 'S': [15,16,16,14,1,1,30],
    'U': [17,17,17,17,17,17,14], 'V': [17,17,17,17,17,10,4],
}


def font(name, glyphs, width, height):
    # Dense ASCII map; unsupported punctuation is a visible question mark.
    bitmap, descriptors = [], ['    {0},']
    fallback = glyphs['?']
    for code in range(32, 127):
        char = chr(code)
        rows = glyphs.get(char, glyphs.get(char.upper(), fallback))
        bits = ''.join(f'{row:0{width}b}' for row in rows)
        bits += '0' * (-len(bits) % 8)
        descriptors.append(f'    {{.bitmap_index = {len(bitmap)}, .adv_w = {width * 16}, '
                           f'.box_w = {width}, .box_h = {height}, .ofs_x = 0, .ofs_y = 0}},')
        bitmap.extend(int(bits[i:i+8], 2) for i in range(0, len(bits), 8))
    lines = [f'static const uint8_t {name}_bitmap[] = {{']
    for start in range(0, len(bitmap), 16):
        lines.append('    ' + ', '.join(f'0x{x:02x}' for x in bitmap[start:start+16]) + ',')
    lines += ['};', f'static const lv_font_fmt_txt_glyph_dsc_t {name}_glyphs[] = {{',
              *descriptors, '};', f'static const lv_font_fmt_txt_cmap_t {name}_cmap[] = {{{{',
              '    .range_start = 32, .range_length = 95, .glyph_id_start = 1,',
              '    .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY,', '}};',
              f'static const lv_font_fmt_txt_dsc_t {name}_dsc = {{',
              f'    .glyph_bitmap = {name}_bitmap, .glyph_dsc = {name}_glyphs,',
              f'    .cmaps = {name}_cmap, .cmap_num = 1, .bpp = 1, .bitmap_format = 0,',
              '};', f'const lv_font_t cornix_font_{name} = {{',
              '    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,',
              '    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,',
              f'    .line_height = {height}, .base_line = 0, .dsc = &{name}_dsc,', '};']
    return '\n'.join(lines)


if __name__ == '__main__':
    small = {char: [int(row, 16) for row in rows] for char, rows in SMALL.items()}
    layer = {char: [row << 1 for row in rows] + [0] for char, rows in small.items()}
    layer.update(LAYER)
    source = '/* SPDX-License-Identifier: MIT\n * Generated by scripts/generate-dongle-fonts.py. */\n'
    source += '#include "compact_fonts.h"\n\n'
    source += font('small', small, 4, 6) + '\n\n' + font('layer', layer, 5, 7) + '\n'
    (ROOT / 'boards/shields/cornix_dongle_display/widgets/compact_fonts.c').write_text(source, encoding='utf-8')
