/* Generated by scripts/encode-dongle-cat.py. See ../ASSETS.md. */
#pragma once
#include <lvgl.h>
#define SALARY_IDLE_COUNT 3
extern const lv_image_dsc_t *salary_idle_frames[3];
#define SALARY_ERROR_COUNT 4
extern const lv_image_dsc_t *salary_error_frames[4];
