/* Generated by scripts/encode-dongle-cat.py. See ../ASSETS.md. */
#pragma once
#include <lvgl.h>
#define SALARY_SLEEP_COUNT 1
extern const lv_image_dsc_t *salary_sleep_frames[1];
#define SALARY_WORK_COUNT 5
extern const lv_image_dsc_t *salary_work_frames[5];
#define SALARY_SNACK_COUNT 23
extern const lv_image_dsc_t *salary_snack_frames[23];
