// Generated by tools/encode-display-assets.py; see design/README.md for artwork credits.
#pragma once
#include <stdint.h>
#define CAT_WIDTH 180
#define CAT_HEIGHT 180
#define CAT_FRAME_BYTES 64800
#define CAT_WORK_FRAMES 21
static const uint16_t cat_work_ends[] = {40,80,120,160,200,240,280,320,360,400,440,520,560,600,640,680,720,760,800,840,880};
#define CAT_SLEEP_FRAMES 35
static const uint16_t cat_sleep_ends[] = {40,80,160,200,280,320,400,440,520,560,600,640,680,760,800,840,920,960,1000,1040,1080,1120,1160,1200,1240,1280,1320,1360,1400,1440,1480,1520,1560,1600,1640};
