#!/usr/bin/env python3
"""Lossless port of StopWatch UI resources. No compiler or network required."""
import argparse
import hashlib
import json
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / 'stopwatch/main/assets'
DEST = ROOT / 'dongle/assets'


def numbers(text):
    text = re.sub(r'/\*.*?\*/|//[^\n]*', '', text, flags=re.S)
    return [int(n, 0) for n in re.findall(r'-?0x[0-9a-fA-F]+|-?\d+', text)]


def array(text, name):
    return re.search(r'\b' + name + r'\[\]\s*=\s*\{(.*?)\};', text, re.S).group(1)


def generate():
    files = {}
    manifest = json.loads((SOURCE / 'manifest.json').read_text())
    rust = ['// Generated by tools/display_assets.py; see assets/README.md.', 'use super::render::{Font, Glyph};']
    for name, entry in manifest.items():
        raw = (SOURCE / f'cat_{name}.bin').read_bytes()
        assert hashlib.sha256(raw).hexdigest() == entry['output_sha256']
        assert (entry['width'], entry['height']) == (180, 180)
        offsets, encoded = [], bytearray()
        # Each row is independently decodable, requiring only a small stripe in RAM.
        for start in range(0, len(raw), 360):
            offsets.append(len(encoded))
            row = struct.unpack('<180H', raw[start:start + 360])
            decoded, x = [], 0
            while x < 180:
                count = 1
                while x + count < 180 and row[x + count] == row[x]:
                    count += 1
                encoded.extend(struct.pack('<BH', count, row[x]))
                decoded.extend([row[x]] * count)
                x += count
            assert tuple(decoded) == row
        offsets.append(len(encoded))
        files[f'{name}.rle'] = struct.pack('<' + 'I' * len(offsets), *offsets) + encoded
        rust.append(f'pub const {name.upper()}_ENDS: &[u16] = &{entry["frame_ends_ms"]};')
        rust.append(f'pub const {name.upper()}: &[u8] = include_bytes!("../assets/{name}.rle");')
    for name, path, bitmap, descriptors in [
        ('NOTO', SOURCE / 'display_font.c', 'bitmap', 'glyphs'),
        ('SMALL', DEST / 'source/lv_font_montserrat_14.c', 'glyph_bitmap', 'glyph_dsc'),
        ('LARGE', DEST / 'source/lv_font_montserrat_28.c', 'glyph_bitmap', 'glyph_dsc'),
    ]:
        text = path.read_text(encoding='utf-8')
        files[f'{name.lower()}.bin'] = bytes(numbers(array(text, bitmap)))
        records = re.findall(r'\{([^{}]+)\}', array(text, descriptors))
        codes = [n + 32 for n in numbers(array(text, 'codes'))] if name == 'NOTO' else list(range(32, 127))
        glyphs = []
        left = right = [0] * len(records)
        if name != 'NOTO':
            left = numbers(array(text, 'kern_left_class_mapping'))
            right = numbers(array(text, 'kern_right_class_mapping'))
            files[f'{name.lower()}_kern.bin'] = bytes(n & 255 for n in numbers(array(text, 'kern_class_values')))
        for index, code in enumerate(codes, 1):
            fields = {k: int(v) for k, v in re.findall(r'\.(\w+)\s*=\s*(-?\d+)', records[index])}
            values = [code, fields['bitmap_index'], fields['adv_w'], fields['box_w'], fields['box_h'], fields['ofs_x'], fields['ofs_y'], left[index], right[index]]
            glyphs.append('Glyph(' + ','.join(map(str, values)) + ')')
        height = int(re.search(r'\.line_height\s*=\s*(\d+)', text).group(1))
        baseline = int(re.search(r'\.base_line\s*=\s*(\d+)', text).group(1))
        kern = '&[]' if name == 'NOTO' else f'include_bytes!("../assets/{name.lower()}_kern.bin")'
        count = 0 if name == 'NOTO' else int(re.search(r'\.right_class_cnt\s*=\s*(\d+)', text).group(1))
        rust.append(f'pub const {name}: Font = Font {{ bitmap: include_bytes!("../assets/{name.lower()}.bin"), glyphs: &[\n' + ',\n'.join(glyphs) + f'], height: {height}, baseline: {baseline}, kern: {kern}, right_classes: {count} }};')
    files['../src/assets.rs'] = ('\n'.join(rust) + '\n').encode()
    return files


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, data in generate().items():
        path = DEST / name
        if args.check:
            assert path.read_bytes() == data, f'Regenerate {path}'
        else:
            path.write_bytes(data)
    print('PASS: UI resources match StopWatch fonts and every animation pixel/frame delay')
