#!/usr/bin/env python3
"""Generate matching RMK configs and Vial layout; Python 3.11+, no compilation."""
import argparse
import json
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs(reset_storage=False):
    shared = (ROOT / "config/layout.toml").read_text(encoding="utf-8")
    layout = tomllib.loads(shared)
    rows = [re.findall(r"\((\d+),(\d+)\)", line) for line in layout["layout"]["map"].splitlines() if line.strip()]
    positions = [pos for row in rows for pos in row]
    assert len(positions) == len(set(positions)) == 50, "Expected 50 unique physical keys"
    for layer in layout["keymap"]["layer"]:
        keys = re.findall(r"\w+\([^)]*\)|\S+", layer["keys"])
        assert len(keys) == 50, f"Layer has {len(keys)} keys, expected 50"
        assert len(layer["encoders"]) == 2
    result = {}
    for target, chip, start, sectors in [
        ("dongle", "esp32s3", 0x3F0000, 16),
        ("peripherals", "nrf52840", 0xD4000, 32),
    ]:
        header = f'''# Generated by tools/generate.py. Edit config/layout.toml instead.
[keyboard]
name = "Cornix RMK StopWatch"
product_name = "Cornix RMK S3"
manufacturer = "Cornix community"
vendor_id = 0x4c4b
product_id = 0x4643
chip = "{chip}"
usb_enable = true

[storage]
enabled = true
start_addr = {start:#x}
num_sectors = {sectors}
clear_storage = {str(reset_storage).lower()}

'''
        result[ROOT / target / "keyboard.toml"] = header + shared
    # Vial coordinates use the same 8x7 logical matrix as RMK (not ZMK's 4x14).
    vial = {
        "name": "Cornix RMK StopWatch", "vendorId": "0x4C4B", "productId": "0x4643",
        "lighting": "none", "matrix": {"rows": 8, "cols": 7},
        "customKeycodes": [
            {"name": name, "shortName": name, "title": title}
            for name, title in [
                ("BT0", "Bluetooth profile 0"), ("BT1", "Bluetooth profile 1"),
                ("BT2", "Bluetooth profile 2"), ("Next BT", "Next Bluetooth profile"),
                ("Prev BT", "Previous Bluetooth profile"), ("Clear BT", "Clear host bond"),
                ("Output", "Switch USB / BLE output"), ("Clear Peer", "Hold 5 seconds to clear split pairing"),
            ]
        ],
        "layouts": {"keymap": [[f"{r},{c}" for r, c in row] for row in rows]},
    }
    # The extra row exposes encoder directions in Vial without consuming matrix keys.
    vial["layouts"]["keymap"].append([
        {"x": 2}, "0,0\n\n\n\n\n\n\n\n\ne", "0,1\n\n\n\n\n\n\n\n\ne",
        {"x": 4}, "1,0\n\n\n\n\n\n\n\n\ne", "1,1\n\n\n\n\n\n\n\n\ne",
    ])
    result[ROOT / "dongle/vial.json"] = json.dumps(vial, indent=2) + "\n"
    result[ROOT / "peripherals/vial.json"] = result[ROOT / "dongle/vial.json"]
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--reset-storage", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in outputs(args.reset_storage).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Regenerate RMK configs: " + ", ".join(stale))
    print("RMK configuration verified" if args.check else "RMK configuration generated")


if __name__ == "__main__":
    main()
